import { DGIssue } from "./types";

// Hardcoded fallback dataset. Used when the live Jira fetch fails
// (bad token, network error, etc.) so the app is always demoable.
// Mirrors a realistic mini sprint with ~10 issues, 4-5 of them blocked,
// across all three blocker sources.

export const sampleIssues: DGIssue[] = [
  {
    id: "sample-1",
    key: "SCRUM-1",
    title: "Set up CI/CD pipeline",
    status: "Done",
    assignee: "Alex Chen",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
  {
    id: "sample-2",
    key: "SCRUM-2",
    title: "Design login screen",
    status: "In Progress",
    assignee: "Priya Nair",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
  {
    id: "sample-3",
    key: "SCRUM-3",
    title: "Finalize contract terms with vendor",
    status: "In Progress",
    assignee: "Bishwa Behera",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
  {
    id: "sample-4",
    key: "SCRUM-4",
    title: "Implement OAuth integration",
    status: "Blocked",
    assignee: "Alex Chen",
    isBlocked: true,
    blockedBy: ["SCRUM-3"],
    blockerSource: "Vendor",
    blockedSince: "2026-08-20",
  },
  {
    id: "sample-5",
    key: "SCRUM-5",
    title: "Approve new pricing model",
    status: "To Do",
    assignee: "Jordan Lee",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
  {
    id: "sample-6",
    key: "SCRUM-6",
    title: "Launch pricing page",
    status: "Blocked",
    assignee: "Priya Nair",
    isBlocked: true,
    blockedBy: ["SCRUM-5"],
    blockerSource: "Business",
    blockedSince: "2026-08-15",
  },
  {
    id: "sample-7",
    key: "SCRUM-7",
    title: "Migrate database schema",
    status: "Blocked",
    assignee: "Sam Rivera",
    isBlocked: true,
    blockedBy: ["SCRUM-1"],
    blockerSource: "Engineering",
    blockedSince: "2026-08-25",
  },
  {
    id: "sample-8",
    key: "SCRUM-8",
    title: "Write onboarding documentation",
    status: "To Do",
    assignee: "Jordan Lee",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
  {
    id: "sample-9",
    key: "SCRUM-9",
    title: "Release mobile app update",
    status: "Blocked",
    assignee: "Sam Rivera",
    isBlocked: true,
    blockedBy: ["SCRUM-4", "SCRUM-7"],
    blockerSource: "Engineering",
    blockedSince: "2026-08-10",
  },
  {
    id: "sample-10",
    key: "SCRUM-10",
    title: "Customer feedback review session",
    status: "Done",
    assignee: "Bishwa Behera",
    isBlocked: false,
    blockedBy: [],
    blockerSource: null,
    blockedSince: null,
  },
];
